FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir \
    biopython \
    pandas

# Create working directories
WORKDIR /app
RUN mkdir -p /app/data

RUN apt-get install -y software-properties-common
RUN sudo add-apt-repository ppa:ondrej/php
RUN sudo apt update
RUN sudo apt upgrade
RUN sudo apt install -y php5.6

RUN apt-get install php5.6-gd php5.6-mysql php5.6-imap php5.6-curl
RUN php5.6-intl php5.6-pspell php5.6-recode php5.6-sqlite3 php5.6-tidy
RUN php5.6-xmlrpc php5.6-xsl php5.6-zip php5.6-mbstring php5.6-soap
RUN php5.6-opcache libicu65 php5.6-common php5.6-json php5.6-readline
RUN php5.6-xml libapache2-mod-php5.6 php5.6-cli 

RUN sudo a2enmod php5.6
RUN sudo service apache2 restart

# Install MolProbity
RUN wget -O install_via_bootstrap.sh https://github.com/rlabduke/MolProbity/raw/master/install_via_bootstrap.sh
RUN ./install_via_bootstrap.sh 4

# Set environment variables
ENV PYTHONPATH=/app
ENV PATH="/app/bin:${PATH}"


